[project]
name = "bench-browser-use"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.11.2",
    "py-browser-automation>=0.3.0",
]
